theme: jekyll-theme-minimal # For supported themes
remote_theme: THEME-NAME # For other Jekyll themes hosted on GitHub
title: Your Site Title
description: A brief description of your site.
url: "https://aikesi128.github.io" # Your site's base URL
baseurl: "/md" # If your site is in a subfolder of your username.github.io
